TAS-1094/Implemented referral system API
socious-io/socious-api pull request #500
Opened 2024-02-29 04:29 UTC by Odeyaloleg

2024-02-29 06:02 UTC, jeyem requested changes

2024-02-29 06:02 UTC, jeyem commented on src/models/referring/index.js
> +const insert = async (referred_profile_id, referred_by_id) => {
code style use camel case  on variable and function parameter use snake case on objects

2024-02-29 06:02 UTC, jeyem commented on src/models/referring/index.js
> +  return app.db?.get(sql`SELECT referred_by_id FROM referrings WHERE referred_profile_id=${referred_profile_id} AND referred_at < now() - INTERVAL '1 year'`)
break query in 3 line please, and change parameter naming, Thanks

2024-02-29 06:02 UTC, jeyem commented on src/routes/organization.js
> +  const referred_by_id = ctx.request.body?.referredBy
camel case variable

2024-03-01 06:06 UTC, jeyem commented on migrations/sqls/20240228103534-add-user-identity-verified-up.sql
> +  referred_by_id uuid NOT NULL REFERENCES users(id),
I refer this to identity too , to make it more general cause referring by org would be possible in future some this put BE open up to do that too if it's been needed

2024-03-25 10:47 UTC, Odeyaloleg commented on src/routes/organization.js
> +    if (!user.identity_verified)
@jeyem Is this fine or better create a function `User.getVerified` to move this check to database layer?

2024-03-25 21:03 UTC, Odeyaloleg commented on migrations/sqls/20240228103534-add-user-identity-verified-up.sql
> +ALTER TABLE offers
Not sure about correctness of this decision

2024-03-26 15:22 UTC, jeyem requested changes

2024-03-29 08:09 UTC, merged